# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# permalink:        /:title/

# Setup
title:            ISSA-DW
tagline:          'ISSA-DW'
description:      'The 2016 International Symposium on  IoT  Systems, Services and Analytics for Developing Worlds (ISSA-DW2016).'
url:              https://issadw.github.io
baseurl:          /2016

author:
  name:           'Kien Nguyen'
  url:            https://twitter.com/ntk148v

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/issadw/issadw.github.io/tree/master/2016
